[package]
name = "gateway-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
gateway-application.workspace = true
gateway-domain.workspace = true
serde_json.workspace = true
serde.workspace = true
sqlx.workspace = true
time.workspace = true
uuid.workspace = true

[dev-dependencies]
sha2.workspace = true
gateway-scheduler.workspace = true
tokio.workspace = true

[lints]
workspace = true
