[package]
name = "gateway-tron"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["k256"] }
async-trait.workspace = true
bs58.workspace = true
gateway-application.workspace = true
gateway-domain.workspace = true
gateway-telemetry.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
k256 = { version = "0.13", features = ["ecdsa"] }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
